### ISSUE TITLE
Docker Extension will not provision on Cent OS 7.2n

### ISSUE THREAD

**Issue by danielstocker** [Azure/azure-docker-extension#104]
(if you would like to reach out inside Microsoft, my alias is dasto)

Dear Docker Extension team,
I am a Support Engineer on a customer case investigating a deployment error for the docker extension on CentOS 7.2n. The deployment works fine on CentOS 7.0, however on the newer 7.2n we seem to get the following deployment error:

_[DockerExtension] 2016/08/17 12:31:15 restarting docker-engine
[executil] 2016/08/17 12:31:15 +++ invoke: systemctl [daemon-reload]
[executil] 2016/08/17 12:31:16 --- invoke end
[executil] 2016/08/17 12:31:16 +++ invoke: systemctl [restart docker]
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
[executil] 2016/08/17 12:31:16 --- invoke end
[DockerExtension] 2016/08/17 12:31:16 ERROR: executing systemctl [restart docker] failed: exit status 1_

I have attached the following logs:

- /var/log/azure-docker-extension-enable.log
- /var/log/waagent.log

Additionally I also ran _systemctl status docker.service_ and _journalctl -xe_ on the problem machine. The output for these is attached too. 

It would be great if you could have a look into this issue. 
My repro environment is still set up and I can give you access if required.

**Comment by ahmetalpbalkan** [comment]
@danielstocker thanks for reporting. I can't see the attachments.

**Comment by danielstocker** [comment]
[journalctl -xe.txt](https://github.com/Azure/azure-docker-extension/files/423206/journalctl.-xe.txt)

attaching logs

**Comment by ahmetalpbalkan** [comment]
@danielstocker `journalctl -xe` seems empty. Can you please give the two files above and `journalctl -au docker.service`?

**Comment by danielstocker** [comment]
@ahmetalpbalkan 

Sorry Ahmet, 
Here they are...

[Docker.zip](https://github.com/Azure/azure-docker-extension/files/423208/Docker.zip)

**Comment by danielstocker** [comment]
![capture](https://cloud.githubusercontent.com/assets/9444698/17747045/dc24f80a-64aa-11e6-8f57-0ff6f1cb2e21.PNG)

Unfortunately this one is empty as well. It's likely due to the fact that docker never ran

**Comment by danielstocker** [comment]
Finally a template that deploys just the Cent OS 7.2n image on an A0 machine - the extension is not yet added and can be deployed via the portal or CLI

**Comment by ahmetalpbalkan** [comment]
@danielstocker I see errors like


```
2016/08/17 12:30:19 ERROR:Exception: [Errno 12] Cannot allocate memory
2016/08/17 12:30:19 Restart agent in 15 seconds
2016/08/17 12:30:34 Azure Linux Agent Version: WALinuxAgent-2.0.18
2016/08/17 12:30:34 Linux Distribution Detected      : centos
2016/08/17 12:30:34 ERROR:Traceback (most recent call last):
2016/08/17 12:30:34 ERROR:  File "/usr/sbin/waagent", line 7162, in main
2016/08/17 12:30:34 ERROR:    WaAgent.Run()
2016/08/17 12:30:34 ERROR:  File "/usr/sbin/waagent", line 6535, in Run
2016/08/17 12:30:34 ERROR:    self.SearchForVMMStartup()
2016/08/17 12:30:34 ERROR:  File "/usr/sbin/waagent", line 6380, in SearchForVMMStartup
2016/08/17 12:30:34 ERROR:    self.TryLoadAtapiix()
2016/08/17 12:30:34 ERROR:  File "/usr/sbin/waagent", line 6340, in TryLoadAtapiix
2016/08/17 12:30:34 ERROR:    retcode,krn=RunGetOutput('uname -r')
2016/08/17 12:30:34 ERROR:  File "/usr/sbin/waagent", line 3006, in RunGetOutput
2016/08/17 12:30:34 ERROR:    output=subprocess.check_output(cmd,stderr=subprocess.STDOUT,shell=True)
2016/08/17 12:30:34 ERROR:  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
2016/08/17 12:30:34 ERROR:    process = Popen(stdout=PIPE, *popenargs, **kwargs)
2016/08/17 12:30:34 ERROR:  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
2016/08/17 12:30:34 ERROR:    errread, errwrite)
2016/08/17 12:30:34 ERROR:  File "/usr/lib64/python2.7/subprocess.py", line 1224, in _execute_child
2016/08/17 12:30:34 ERROR:    self.pid = os.fork()
2016/08/17 12:30:34 ERROR:OSError: [Errno 12] Cannot allocate memory
2016/08/17 12:30:34 ERROR:
2016/08/17 12:30:34 ERROR:Exception: [Errno 12] Cannot allocate memory
```

in the waagent.log. Is your VM running low on memory (docker will fail if your machine does not have enough memory)? I also see diagnostics extension installation failures (that is probably not relevant). Can you try `journalctl -au docker`

**Comment by ahmetalpbalkan** [comment]
@danielstocker it looks like the docker installation was also not healthy, even though `yum` exited successfully. I bet the installation also got impaired by out of memory issues.

```
[executil] 2016/08/17 12:28:37 +++ invoke: /bin/sh [-c curl -sSL https://get.docker.com/ | sh]

+ sh -c 'sleep 3; yum -y -q install docker-engine'
warning: /var/cache/yum/x86_64/7/docker-main-repo/packages/docker-engine-selinux-1.12.0-1.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Public key for docker-engine-selinux-1.12.0-1.el7.centos.noarch.rpm is not installed
Importing GPG key 0x2C52609D:
 Userid     : "Docker Release Tool (releasedocker) <docker@docker.com>"
 Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d
 From       : https://yum.dockerproject.org/gpg
/var/tmp/rpm-tmp.QaTQ0K: line 8:  1575 Killed                  /usr/sbin/semodule -n -s targeted -i $MODULES
restorecon:  lstat(/var/lib/docker) failed:  No such file or directory
warning: %post(docker-engine-selinux-1.12.0-1.el7.centos.noarch) scriptlet failed, exit status 255
Non-fatal POSTIN scriptlet failure in rpm package docker-engine-selinux-1.12.0-1.el7.centos.noarch
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!
```

**Comment by ahmetalpbalkan** [comment]
@danielstocker what I can suggest is:

- make sure the VM has enough memory
- uninstall the extension from PowerShell/CLI/API/Portal
- run `yum -y -q remove docker-engine.x86_64` to uninstall remnants of docker engine (if any)
- add the extension back.

and it should work

**Comment by ahmetalpbalkan** [comment]
I can repro this without templates etc.

docker installs fine
```
+++ invoke: /bin/sh [-c curl -sSL https://get.docker.com/ | sh]
+ sh -c 'sleep 3; yum -y -q install docker-engine'
warning: /var/cache/yum/x86_64/7/docker-main-repo/packages/docker-engine-selinux-1.12.0-1.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Public key for docker-engine-selinux-1.12.0-1.el7.centos.noarch.rpm is not installed
Importing GPG key 0x2C52609D:
 Userid     : "Docker Release Tool (releasedocker) <docker@docker.com>"
 Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d
 From       : https://yum.dockerproject.org/gpg
restorecon:  lstat(/var/lib/docker) failed:  No such file or directory
warning: %post(docker-engine-selinux-1.12.0-1.el7.centos.noarch) scriptlet failed, exit status 255
Non-fatal POSTIN scriptlet failure in rpm package docker-engine-selinux-1.12.0-1.el7.centos.noarch

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!
```

`systemctl restart docker` does not work:
```
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
```

logs:

```
# journalctl -au docker
-- Logs begin at Wed 2016-08-17 18:14:17 UTC, end at Wed 2016-08-17 18:36:31 UTC. --
Aug 17 18:33:45 centos72n systemd[1]: Starting Docker Application Container Engine...
Aug 17 18:33:45 centos72n docker[1702]: time="2016-08-17T18:33:45.633380388Z" level=fatal msg="no sockets found via socket activation: make sure the service was started by systemd"
Aug 17 18:33:45 centos72n systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Aug 17 18:33:45 centos72n systemd[1]: Failed to start Docker Application Container Engine.
Aug 17 18:33:45 centos72n systemd[1]: Unit docker.service entered failed state.
Aug 17 18:33:45 centos72n systemd[1]: docker.service failed.
```

**Comment by colemickens** [comment]
This is a fun one: https://github.com/docker/docker/issues/23793

**Comment by ahmetalpbalkan** [comment]
@colemickens I wonder if related at all. I'm adding the extension minutes after the VM is provisioned.

**Comment by colemickens** [comment]
Hm, on closer look, they are *slightly* different error messages. Does docker start if you ssh in and manually issue `sudo systemctl start docker` though?

**Comment by ahmetalpbalkan** [comment]
Trying on a clean VM **without DockerExtension**:

- Image: openlogic:CentOS:7.2n:7.2.20160629
- CentOS Linux release 7.2.1511 (Core) - kernel: 3.10.0-327.22.2.el7.x86_64

```
# curl -sSL https://get.docker.com/ | sh
+ sh -c 'sleep 3; yum -y -q install docker-engine'
warning: /var/cache/yum/x86_64/7/docker-main-repo/packages/docker-engine-selinux-1.12.0-1.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Public key for docker-engine-selinux-1.12.0-1.el7.centos.noarch.rpm is not installed
Importing GPG key 0x2C52609D:
 Userid     : "Docker Release Tool (releasedocker) <docker@docker.com>"
 Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d
 From       : https://yum.dockerproject.org/gpg
restorecon:  lstat(/var/lib/docker) failed:  No such file or directory
warning: %post(docker-engine-selinux-1.12.0-1.el7.centos.noarch) scriptlet failed, exit status 255
Non-fatal POSTIN scriptlet failure in rpm package docker-engine-selinux-1.12.0-1.el7.centos.noarch

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!
```

```
# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://docs.docker.com
```

```
# systemctl restart docker

# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-08-17 18:50:45 UTC; 6s ago
     Docs: https://docs.docker.com
 Main PID: 1637 (dockerd)
   Memory: 18.5M
   CGroup: /system.slice/docker.service
           ├─1637 /usr/bin/dockerd
           └─1641 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim doc...

Aug 17 18:50:43 centos72n1 dockerd[1637]: time="2016-08-17T18:50:43.571104948Z" level=warning msg="mountp...und"
Aug 17 18:50:43 centos72n1 dockerd[1637]: time="2016-08-17T18:50:43.571470790Z" level=info msg="Loading c...rt."
Aug 17 18:50:43 centos72n1 dockerd[1637]: time="2016-08-17T18:50:43.833842965Z" level=warning msg="Running mo...
Aug 17 18:50:44 centos72n1 dockerd[1637]: time="2016-08-17T18:50:44.097401498Z" level=info msg="Firewalld...lse"
Aug 17 18:50:44 centos72n1 dockerd[1637]: time="2016-08-17T18:50:44.768742840Z" level=info msg="Default b...ess"
Aug 17 18:50:45 centos72n1 dockerd[1637]: time="2016-08-17T18:50:45.307604974Z" level=info msg="Loading c...ne."
Aug 17 18:50:45 centos72n1 dockerd[1637]: time="2016-08-17T18:50:45.307795315Z" level=info msg="Daemon ha...ion"
Aug 17 18:50:45 centos72n1 dockerd[1637]: time="2016-08-17T18:50:45.307838540Z" level=info msg="Docker da...12.0
Aug 17 18:50:45 centos72n1 dockerd[1637]: time="2016-08-17T18:50:45.350741574Z" level=info msg="API liste...ock"
Aug 17 18:50:45 centos72n1 systemd[1]: Started Docker Application Container Engine.
Hint: Some lines were ellipsized, use -l to show in full.
```

```
systemctl stop docker
```

Edit `/usr/lib/systemd/system/docker.service`, `ExecStart=/usr/bin/dockerd` line to: 

    ExecStart=/usr/bin/docker daemon -H=fd://

This is what DockerExtension currently does. But it causes failure:

```
# systemctl daemon-reload

# systemctl restart docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

# systemctl status -l docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-08-17 18:52:48 UTC; 57s ago
     Docs: https://docs.docker.com
  Process: 1809 ExecStart=/usr/bin/docker daemon -H=fd:// (code=exited, status=1/FAILURE)
 Main PID: 1809 (code=exited, status=1/FAILURE)

Aug 17 18:52:47 centos72n1 systemd[1]: Starting Docker Application Container Engine...
Aug 17 18:52:48 centos72n1 docker[1809]: time="2016-08-17T18:52:48.245582841Z" level=fatal msg="no sockets found via socket activation: make sure the service was started by systemd"
Aug 17 18:52:48 centos72n1 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Aug 17 18:52:48 centos72n1 systemd[1]: Failed to start Docker Application Container Engine.
Aug 17 18:52:48 centos72n1 systemd[1]: Unit docker.service entered failed state.
Aug 17 18:52:48 centos72n1 systemd[1]: docker.service failed.
```

Changing `fd://` to `unix:///var/run/docker.sock` seems to have worked:

```
# systemctl daemon-reload

# systemctl restart docker

# systemctl status -l docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-08-17 18:54:34 UTC; 2s ago
     Docs: https://docs.docker.com
 Main PID: 1843 (dockerd)
   Memory: 13.3M
   CGroup: /system.slice/docker.service
           ├─1843 dockerd -H=unix:///var/run/docker.sock
           └─1850 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc
```

This is definitely a bug introduced upstream and has nothing to do with the extension. `-H=fd://` argument is supposed to work.

@danielstocker I'm going to close this issue and add these details to https://github.com/docker/docker/issues/23793 I advise your customer to hit `Subscribe` button on that issue page and follow the updates.

**Comment by ahmetalpbalkan** [comment]
@danielstocker  Closing as I moved the bug report to https://github.com/docker/docker/issues/23793#issuecomment-240543358

To give you more info, on "all" systemd systems we run docker engine as `docker daemon -H=fd://` arguments. This includes CoreOS, Ubuntu 16.04, CentOS/RHEL 7 and so on.

If we don't get this resolved on docker side and your customer needs it, we can consider patching it as just running `dockerd` command with no arguments (I bet docker figures it out).

I'm not sure if patching it as `-H=unix:///var/run/docker.sock` will be compatible on all distros. So let us know if your customer really needs it, otherwise it's just yet another case that we got broken again by upstream.

**Comment by ahmetalpbalkan** [comment]
Reopening. Apparently `-H fd://` is not valid on CentOS anymore as docker removed socker activation from the centos part of the `get.docker.com` installation script.

@colemickens  My plan here is the following:

- Publish Docker Extension 1.2 (minor bump) so that only new VMs get it (more below)
- Update all distros to just have just `dockerd`; do not add `-H=fd://` or `-H=unix://` (both for systemd and upstart) anymore.
- Add centos72 to the list of distros tested in integration tests and update the list

Normally we rarely release minor versions (it means new version) and only new VMs that are specifying `autoUpgradeMinorVersion:true` or `v:1.*`  get it. But in this case, if we release it as a hotfix, the extension will realize the `docker.service` (or similarly the upstart file) is not in the desired shape (e.g. does not start like `ExecStart=dockerd`) and it will update the unit file on the next time extension is enabled (e.g. VM reboot). If an older version of docker is installed on the VM already, things will fail and we'll be breaking the user's environment.

Therefore releasing this as a minor version is better. On the other hand, we still support old versions of CoreOS and those definitely don't have `dockerd` yet. Maybe I'll add an override to `coreos` driver saying keep using `docker daemon` command for now. In parallel, I'll ask docker how long `docker daemon` will be around but I'm pretty sure they'll just deprecate it at some version without a major release.

**Comment by ahmetalpbalkan** [comment]
This will go out as `v1.2.0` soon.

**Comment by ahmetalpbalkan** [comment]
version `1.2.0` is now in production. The problem on CentOS should be resolved now.
