### ISSUE TITLE
Add retry to docker compose download

### ISSUE THREAD

**Issue by srimathiS** [Azure/azure-docker-extension#110]
Deploying the extension in azurestack fails intermittently due to unable to download docker compose. Per our discussion on the email thread it would be good to have retries on this logic to avoid failure during network glitches

**Comment by guillemsola** [comment]
I've seen this issue too. Is there any reason why the download fails? github is usually available.

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
