### ISSUE TITLE
pkg/vmextension: cut dependency to openssl in decoding private settings

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-docker-extension#111]
Not an extension issue but about base vm extension utils.

[`unmarshalProtectedSettings`](https://github.com/Azure/azure-docker-extension/blob/523d8c6a5c142c7e3d434567a96a199736871fbf/pkg/vmextension/handlersettings.go#L111-L144) has dependency to `openssl smime -decrypt` functionality.

I am not sure if this can be implemented in golang today. Last time we checked, the relevant PKCS#7 functionality was not available in Go and https://github.com/fullsailor/pkcs7 does not recognize our key/cert format: https://github.com/fullsailor/pkcs7/issues/3

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
