### ISSUE TITLE
[Question] Availability on Azure Germany Cloud

### ISSUE THREAD

**Issue by Gemakk** [Azure/azure-docker-extension#114]
Are there plans to make this extension available on Azure Germany Cloud?  Otherwise, what's the easiest way to adapt this extension into a CustomScript?

**Comment by boumenot** [comment]
Hi @Gemakk , thanks for reaching out to us, and apologies for taking so long to respond.  I believe it is just an oversight on our part as to why this extension has not been released to the Azure German cloud.  I just submitted a fix for another issue, and I will ensure that a version with this fix is rolled out to the German cloud too.

**Comment by Gemakk** [comment]
Hi @boumenot that's wonderful news.  Is there a known deployment schedule for the German cloud, or is it out of your control/knowledge?

**Comment by boumenot** [comment]
I initiate the process, so it's mostly within my control.  I'll give you a heads up once I have started.

**Comment by boumenot** [comment]
Deployment has been kicked off to Germany Central, and will reach Germay Northeast in about a day assuming the telemetry looks good.

**Comment by Gemakk** [comment]
Thanks a lot!  I confirm it's working for Germany Central now.

**Comment by optiomas** [comment]
Hello! This extension is not available in Germany Northeast region yet, despite being available in Germany Central. Would you be able to roll this out some time soon?

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
