### ISSUE TITLE
Would be great to allow configuration of 1.12 swarm mode 

### ISSUE THREAD

**Issue by khowling** [Azure/azure-docker-extension#115]
I've been using the extension very successfully with a VM scaleset, but I then need to ssh into each node and run a docker init/join.

would be great to allow something like this in settings: node 0 will init the swarm, node 1 to join as a master, and all others to join as workers.

{ "docker": 
   "swarmmode": "true",
   "vmss_masters": [0,1],
}

**Comment by colemickens** [comment]
@khowling It seems like you might be interested in [the Azure Container Service](https://azure.microsoft.com/en-us/services/container-service/).

We are looking at supporting Swarm Mode in the future. If you want to follow that, you could file a feature request against the ACS repo: https://github.com/Azure/ACS

Alternatively, we are working towards supporting Swarm Mode in the open-source core of the Azure Container Service, which is called [ACS-Engine](https://github.com/Azure/ACS-Engine). If you wanted, you could also file a feature request there and you can potentially follow along with the development effort.

Let us know if that provides some clarity. I think that orchestrating Swarm Mode is likely out-of-scope for this extension.

**Comment by khowling** [comment]
@colemickens  makes sense, thanks, I'll follow ACS for the swarm mode & close this request.

FYI, I often want to create small demo/test environments. Here is a script to deploy a 2 node vmss+docker-ext, init the swarm & setup the variables for running the docker cli locally: https://github.com/khowling/springboot_backend/blob/master/env_setup/azure_vmss_swarm.sh
