### ISSUE TITLE
TLS certs are optional for ARM template but mandatory in portal

### ISSUE THREAD

**Issue by larryms** [Azure/azure-docker-extension#118]
The TLS certs are an optional parameter when deploying via the ARM template, but if you use the azure portal to provision a Linux server and use the Docker extension, the certs are mandatory fields and the VM cannot be provisioned without them.

**Comment by boumenot** [comment]
I'll raise the issue with the Portal team.  The configuration that drives the Portal UI should not require values that the extension does not require.

**Comment by boumenot** [comment]
The previous maintainer made these values required in the portal vs. optional in the scripts.  I do not have the context as to why. I assume it was to ensure a working experience, and to make the extension's requirement clearer to the end-user.  This seems reasonable to me.

Could you detail you scenario more?  I would like to understand the trade-off to making these values optional in the portal

**Comment by larryms** [comment]
@boumenot, couple of thoughts:
- I think the portal & the scripts should be consistent; either a parameter is required in both, or it's optional in both.  Otherwise it gets very confusing.
- That being said, if I had a choice I'd like to see the certs as optional in both scenarios, as this makes it easier to use the docker extension for learning, experimentation, prototyping, and development.  Nothing really more specific than that.   
Alternatively, if the portal could automatically create the TLS certs, that would probably remove the need to make them optional (similar to the cli command 'azure vm docker create' which creates the certs on the fly)

**Comment by boumenot** [comment]
I prefer consistency, and auto-generated too.  I will raise the issue with our Portal team.  

I still do not see the value with optional.  If the intent is to experiment with Docker, then just install Docker.  The extension provides no value add in that case, and the extension itself just executes the Docker install script.

```sh
curl -sSL https://get.docker.com/ | sh
```

I am in sticky situation of having to break compatibility, or bump the major version to follow semantic versioning guidelines.  I dislike either of those. :(

**Comment by larryms** [comment]
Good point; you've convinced me:  for learning/experimenting, just install docker.
The value the extension can bring for learning scenarios is to auto-generate and install the TLS certs, thus I think we're in agreement that it would be nice if the portal could do this.  Not a dealbreaker if it can't though, since you can do it with the cli.

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
