### ISSUE TITLE
Cannot get protected settings to work

### ISSUE THREAD

**Issue by gvinsot** [Azure/azure-docker-extension#123]
Hi,

I cannot get protected Environment variables to work : either there is not enough documentation on it, either it does not work : my WordPress docker container is not getting the setting and shuts down.

When I use the same environment with normal (unprotected) settings, it works perfectly.

There does'nt seem to be an integration test on it. (I'm using extension in case of a Virtual Machine Scaleset)

Best regards,
Gildas

**Comment by gvinsot** [comment]
Following Template not working for me:
{
			"type": "Microsoft.Compute/virtualMachines/extensions",
			"name": "wordpressdocker",
			"properties": {
				"publisher": "Microsoft.Azure.Extensions",
				"type": "DockerExtension",
				"typeHandlerVersion": "1.2",
				"autoUpgradeMinorVersion": true,
				"protectedSettings": {
					"environment": {
						"WORDPRESS_DB_HOST": "[parameters('existingMySqlIp')]",
						"WORDPRESS_DB_PASSWORD": "[parameters('wordpressUserName')]",
						"WORDPRESS_DB_USER": "[parameters('wordpressUserPassword')]"
					}
				},
				"settings": {
					"compose": {
						"wordpress": {
							"image": "wordpress",
							"ports": ["80:80"],
							"restart": "always"
						}
					}
				}
			}
		}

**Comment by gvinsot** [comment]
working:
{
	"type": "Microsoft.Compute/virtualMachines/extensions",
	"name": "wordpressdocker",
	"properties": {
		"publisher": "Microsoft.Azure.Extensions",
		"type": "DockerExtension",
		"typeHandlerVersion": "1.2",
		"autoUpgradeMinorVersion": true,
		"settings": {
			"compose": {
				"wordpress": {
					"image": "wordpress",
					"environment": {
						"WORDPRESS_DB_PASSWORD": "[parameters('existingMySqlIp')]",
						"WORDPRESS_DB_HOST": "[parameters('wordpressUserName')]",
						"WORDPRESS_DB_USER": "[parameters('wordpressUserPassword')]"
					},
					"ports": ["80:80"],					
					"restart": "always"
				}
			}
		}
	}
}

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
