### ISSUE TITLE
Unable to redeploy failed docker-compose settings

### ISSUE THREAD

**Issue by Teodelas** [Azure/azure-docker-extension#124]
Hi,

I realize that the docker-extension is not meant to replace DevOps.  If the docker-extension fails due to docker-compose not running successfully (image not found), subsequent deployments won't update the docker-compose.yml file.  In other words, if I fix the image name in my ARM template and re-deploy the extension, docker-compose.yml isn't updated.
teodelas@microsoft.com

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
