### ISSUE TITLE
Redeploy from ARM template does not copy pem's in the correct format

### ISSUE THREAD

**Issue by bmmathe** [Azure/azure-docker-extension#125]
Deploying using the document at https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-dockerextension works great.

However if you then download the template from the Portal and reissue the exact same deployment for another host and copy in the same cert information from the parameters file from the template.zip, the pem is malformed in the new host.  It copies the data exactly as specified in the template which is not acceptable as an openssl cert.  It appears as though the deployment instructions in the link above causes a conversion of the base64 cert to the proper openssl format which the ARM template deployment does not.

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
