### ISSUE TITLE
Docker extension times out

### ISSUE THREAD

**Issue by rolandoldengarm** [Azure/azure-docker-extension#127]
I'm deploying to Azure China, and using [this](https://github.com/Azure/azure-quickstart-templates/tree/master/docker-neo4j) as a template.
I've specified environment-name in the settings with AzureChinaCloud.

But, installation times out, in Azure I see:
```
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningTimeout",
        "message": "Provisioning of VM extension 'DockerExtension' has timed out. Extension installation may be taking too long, or extension status could not be obtained."
      }
    ]
  }
}
```
In /var/log/azure-docker-extension-enable.log the last lines say:
```
[DockerExtension] 2017/04/19 23:06:13 Using compose yaml:>>>>>
neo4j:
  image: tpires/neo4j
  ports:
  - 7474:7474
  - 7473:7473
  volumes:
  - /datadisk:/var/lib/neo4j/data

<<<<<
[DockerExtension] 2017/04/19 23:06:13 Setting docker-compose environment variable "COMPOSE_HTTP_TIMEOUT"="600".
[DockerExtension] 2017/04/19 23:06:13 Setting docker-compose environment variable "COMPOSE_PROJECT_NAME"="compose".
[executil] 2017/04/19 23:06:13 +++ invoke: /usr/local/bin/docker-compose [-f /etc/docker/compose/docker-compose.yml up -d]
Pulling neo4j (tpires/neo4j:latest)...
```
How can we make this work please?

**Comment by colemickens** [comment]
Isn't Docker Hub effectively blocked in China too?

**Comment by rolandoldengarm** [comment]
@colemickens it is working randomly. I've had it working after a lot of tries...

**Comment by rolandoldengarm** [comment]
I've tried again, getting this error:
```
Pulling neo4j (tpires/neo4j:latest)...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 56, in main
  File "compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "compose/cli/docopt_command.py", line 26, in dispatch
  File "compose/cli/main.py", line 191, in perform_command
  File "compose/cli/main.py", line 657, in up
  File "compose/project.py", line 318, in up
  File "compose/service.py", line 351, in execute_convergence_plan
  File "compose/service.py", line 252, in create_container
  File "compose/service.py", line 279, in ensure_image_exists
  File "compose/service.py", line 770, in pull
  File "compose/progress_stream.py", line 18, in stream_output
  File "compose/utils.py", line 52, in split_buffer
  File "compose/utils.py", line 28, in stream_as_text
  File ".tox/py27/lib/python2.7/site-packages/docker/client.py", line 217, in _stream_helper
  File ".tox/py27/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 271, in read
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
docker-compose returned -1
[executil] 2017/04/20 01:29:01 --- invoke end
[DockerExtension] 2017/04/20 01:29:01 ERROR: 'docker-compose up' failed: executing /usr/local/bin/docker-compose [-f /etc/docker/compose/docker-compose.yml up -d] failed: exit status 255. Check logs at /var/log/azure/Microsoft.Azure.Ext$
[DockerExtension] 2017/04/20 01:29:01 Cleaned up .seqnum file.
[DockerExtension] 2017/04/20 01:29:01 Exiting with code 1.
```

**Comment by colemickens** [comment]
Further evidence of GFW: `('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))`

I think you got lucky if it was working at all. Every deployment of Docker in China that I'm aware of uses a China-local docker registry/mirror.

**Comment by rolandoldengarm** [comment]
@colemickens yeah it must be GFW.

I've now tried to load the image offline (via docker load), and then run the deployment again. But it will pull the image again, failing...
When I run "docker images", the image is there. 

I'm new to Docker & Docker Compose, but I thought it wouldn't pull images if they are already loaded? Or am I running it as wrong account?

**Comment by colemickens** [comment]
From here: https://github.com/docker/compose/issues/1116 it looks like there is a `--pull` option.

But from looking here, it's not used: https://github.com/Azure/azure-docker-extension/blob/master/op-enable.go#L290 (unless you're somehow specifying it)

From just testing locally, it looks like it's important that you "save" with the exact same tag as you use in your `compose-up` yaml.

Can you post the yaml and the save/load commands you used?

**Comment by rolandoldengarm** [comment]
@colemickens I've re-ran it a couple of times, and it's deployed now... So it's just a matter of re-trying :)

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
