### ISSUE TITLE
Enhancement: possibility to specify docker storage folder

### ISSUE THREAD

**Issue by lionelperrin** [Azure/azure-docker-extension#128]
Hello,

I'd like to use the data disk of my vm as storage folder for docker.
I don't think there is any option to configure the extension for the time being. Do you think this could be added in the future ?

Regards,

Lionel

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
