### ISSUE TITLE
Extensions settings not updated on scale set

### ISSUE THREAD

**Issue by guillemsola** [Azure/azure-docker-extension#129]
I originally created an scale set with Docker extensions. The I decided to run it again updating the settings to enable port 2375.

```json
"extensionProfile": {
            "extensions": [
              {
                "name": "docker",
                "properties": {
                  "publisher": "Microsoft.Azure.Extensions",
                  "type": "DockerExtension",
                  "typeHandlerVersion": "1.0",
                  "autoUpgradeMinorVersion": true,
                  "settings": {
                    "docker": {
                      "port": "2375"
                    }
                  }
                }
              }
            ]
          }
```

If I check in the portal I can see that these changes have been propagated to the model, however these settings are not applied to the machine

In ```/var/log/azure/Microsoft.Azure.Extensions.DockerExtension/docker-extension.log``` I can see that changes are still applied with the original settings as the ```-H tcp://0.0.0.0:2375``` daemon binding is missing.

```
[DockerExtension] 2017/05/28 08:20:39 Updating daemon args to: -H=fd://
```

**Comment by guillemsola** [comment]
To add more details, I finally had to delete the scale set and deploy it again to apply the changes.

I also removed the extension with az cli and appeared as removed in the ARM model but machines still had docker and was impossible to redeploy the extension with another parameters.

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
