### ISSUE TITLE
Make intallation timeout more flexable

### ISSUE THREAD

**Issue by shhsu** [Azure/azure-docker-extension#134]
We have a linux image that tries to update itself on starting up. It took 11 minutes for it to update itself. Meanwhile the docker extension only attempt to install docker for 6 minutes and gives up. I am hoping that we can have a more flexable retry logic like this
https://github.com/Azure/azure-docker-extension/pull/133

**Comment by shhsu** [comment]
/cc
@sivagms 
@yuwaMSFT2

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
