### ISSUE TITLE
This extension is out of date

### ISSUE THREAD

**Issue by NicolasDorier** [Azure/azure-docker-extension#135]
This extension has been un maintained since almost 1 year and so does not support v3 docker-compose.

Do you plan to keep it maintained? if not, please fix erroneous the documentation about it. I lost lots of time making it works just to see that my docker-compose was not working.

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).

**Comment by NicolasDorier** [comment]
For people finding this issue you check how I use customScripts as replacement on  https://github.com/btcpayserver/btcpayserver-azure/blob/master/entrypoint.sh#L76
