### ISSUE TITLE
How to resolve a "bad certificate" error

### ISSUE THREAD

**Issue by mpilant** [Azure/azure-docker-extension#28]
I'm in the process of trying to set up an Azure Ubuntu VM with the Docker extensions and everything seems to go fine until I try to do a remote "docker info" command (using the information here: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-docker-with-portal/) to test the Azure host.  (Doing it on the Azure VM works fine, so I know Docker is there.)

My local client is also an Ubuntu 14.04 LTS system, and I can successfully SSH to the Azure VM.  However when I use the command:
docker --tls -H=tcp://my-ubuntu-system.cloudapp.net:4243 info
I get the "remote error: bad certificate" error.

I have verified the certificates in the Azure VM (in /etc/docker) are indeed the correct ones, so the question is: which certificate is bad?

Is there some certificate I don't have in place on the client system to access the remote host?

Thanks in advance.

**Comment by mpilant** [comment]
On a hunch, I figured out the solution.  I needed to add the appropriate certificates to the .docker home directory for the account from which I was trying to access the Azure VM.

Once the certificates were in ~/.docker/ all was well.

**Comment by ahmetalpbalkan** [comment]
@mpilant actually we just pushed a brand new DockerExtension to production today (see README for how to use the new one).
