### ISSUE TITLE
Version of docker-compose incompatible with current version of Docker for registry actions

### ISSUE THREAD

**Issue by stevenewey** [Azure/azure-docker-extension#41]
Docker moved where it stored the authentication credentials for the registry in version 1.7.0. The version of docker-compose provided by the Azure extension doesn't know about the change and is unable to pull private images. Upgrading to the latest docker-compose should resolve the issue. See https://github.com/docker/compose/issues/1590

**Comment by ahmetalpbalkan** [comment]
@stevenewey thanks for reporting. I just started pushing the fix.

**Comment by ahmetalpbalkan** [comment]
@stevenewey I just pushed DockerExtension **v1.0.1507151643** to production (it's still replicating across regions but it should be ready in US/Europe regions and the rest should be completed shortly in an hour.)

If you remove/add the extension again or create a new VM that version should be picked up and it installs docker-compose 1.3.2.

Please let us know if you encounter any issues. Sorry for the inconvenience.

**Comment by stevenewey** [comment]
@ahmetalpbalkan That's great, thank you.

It solves the issue and has me up and running. Thanks for the quick turnaround.
