### ISSUE TITLE
Removing Azure VM Endpoint causes Docker container to exit

### ISSUE THREAD

**Issue by mpilant** [Azure/azure-docker-extension#45]
I've come across something and I'm not sure if it is a bug or a feature by design.
If I create an Azure Ubuntu 14.04 LTS VM with the (latest) Docker Extension and a running app in a Docker container, when I delete the VM endpoint, the Docker container exits.  As there endpoint / port is quiet (no traffic), I'm not sure why this should cause the container to exit.  The app in the container does not have any kind of heartbeat.
Does the Docker Extension implementation check the port for a corresponding VM endpoint?

**Comment by ahmetalpbalkan** [comment]
No we don't do anything special. We create the compose specification you provided using 

    docker-compose up -d

and do not touch the containers. If your container is exiting please use `docker logs CONTAINERID` to see what is going on inside your container.

**Comment by ahmetalpbalkan** [comment]
Closing as it's not related the extension.
