### ISSUE TITLE
Docker Swarm behind Azure load balancing

### ISSUE THREAD

**Issue by mpilant** [Azure/azure-docker-extension#48]
For testing, I recently set up a Docker Swarm in a load balanced Azure Cloud Service consisting of 5 VMs, all running Ubuntu 14.04 LTS with the Azure Docker VM Extension.  Prior to trying to create the swarm, I was able to configure a load balanced cloud service with 4 VMs which worked fine.  (The fifth node was added as the swarm master.)  This did get a little interesting, making sure all of the ports chosen for the swarm nodes (and the use of the [Azure] internal IP address) are appropriate.
While the swarm appeared to be created/joined/managed correctly, all containers deployed to the swarm master were not "sent" to the swarm nodes, but were deployed on the swarm master.  BTW, by correctly, I mean the swarm agent was running on all the swarm nodes, the swarm list on the swarm master was correct, etc.
The question I have is: has anyone successfully deployed a swarm behind Azure LB?
One test I need to do is to see if I can deploy a swarm without LB.
Thanks in advance.
- Mark

**Comment by ahmetalpbalkan** [comment]
>  all containers deployed to the swarm master were not "sent" to the swarm nodes, but were deployed on the swarm master.

You are most likely talking to the Docker engine running on the master node. You should not do that, instead you should be exposing ports from the `swarm manage` container and docker client should talk to that. 

I don't see any reason why this wouldn't work when done correctly. At the end of the day, it's all HTTP servers. However, I'm not sure if anyone has done it before.

**Comment by mpilant** [comment]
@ahmetalpbalkan Ah, that would make sense.  So, if I understand you correctly, the deployment of containers to the swarm should be done using the port for "swarm manage" not Docker on the swarm manager.  Did I get this right?

**Comment by ahmetalpbalkan** [comment]
I think so. I think your question is mostly around swarm itself, please refer to their docs and create local nodes using docker-machine to experiment more. Meanwhile, we have started developing a docker-swarm ARM template here: https://github.com/Azure/azure-quickstart-templates/tree/master/docker-swarm-cluster-simple and we have plans to add Azure LB support at some point, too. Please feel free to try that out.

**Comment by mpilant** [comment]
Well, maybe swarm.  I wasn't sure if the "problem" was with swarm, Azure Docker VM extension, Ubuntu, or any of the pieces involved.  I have read the swarm docs a number of times, as well as a bunch of other pages showing examples, but there are some aspects, like the port for swarm manage, which are not at all clear.

**Comment by mpilant** [comment]
One confusing reference is here: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-docker-swarm/
The join is done using the IP address and port 2376.  Yet the swarm list shows the IP address and port 2375.
The testing I've done seems to indicate the information in the swarm list comes from the join, but the example seems to indicate the port may come from the swarm manage (since it uses 2375).  This may be a simple error, but I'm not sure.

**Comment by ahmetalpbalkan** [comment]
Closing as it's not related the extension.
