### ISSUE TITLE
Spurious = added to Env when parsing JSON file

### ISSUE THREAD

**Issue by bureado** [Azure/azure-docker-extension#49]
If I pass the following JSON file to the extension, the environment variable is effectively passed to the container but has a trailing = (as per `docker inspect`)

```json
{   
    "compose": {
        "portal" : {
            "image" : "centurylink/drupal",
            "ports" : ["80:80"],
            "links" : ["database"]
        },
        "database": {
            "image": "centurylink/mysql",
            "environment": ["MYSQL_DATABASE: portal_db"]
        }
    }
}
```

And

```
azureuser@jmp-tr01:~$ sudo docker inspect compose_database_1 | grep MYSQL_DATABASE
            "MYSQL_DATABASE: portal_db=",
```

**Comment by ahmetalpbalkan** [comment]
@bureado because you're specifying it incorrectly. http://docs.docker.com/compose/env/

it should be:

    "environment": ["MYSQL_DATABASE=portal_db"]

**Comment by bureado** [comment]
Yes, I was confused by the first syntax (not arrays) in https://docs.docker.com/compose/yml/#environment - my bad.

**Comment by ahmetalpbalkan** [comment]
@bureado there are two ways supported:

![image](https://cloud.githubusercontent.com/assets/159209/8922128/f768db10-3493-11e5-860c-6b96dd0a99a9.png)


I find the second way safer, to do the first way, you need to do:

```json
{
  "environment": {
    "RACK_ENV": "development",
    "SESSION_SECRET": "foo"
  }
}
```

You can use http://yamltojson.com/ for practicing.
