### ISSUE TITLE
--daemon is now just daemon

### ISSUE THREAD

**Issue by stevenewey** [Azure/azure-docker-extension#50]
Docker 1.8.0 just came out and they've changed the daemon argument for starting up the Docker daemon process, removing the '--' from the option. Unfortunately this means that out of the box the Azure Docker Extension is no longer able to start the docker daemon process because of the 'bad' option.

On a broader topic, always installing the latest version of Docker makes using the extension a little bit scary if you're doing a deployment and a new version of Docker appears (as it has today) and breaks everything! Longer term, some way of pinning Docker versions would be really useful.

EDIT: They've actually moved the 'daemon' option into the upstart init script so it's no longer necessary at all in the DOCKER_OPTS in /etc/default/docker.

**Comment by ahmetalpbalkan** [comment]
@stevenewey thanks for reporting. I'm working on a fix away. 

We're also looking for a way to install a specific version of docker using the `wget|sh` script they have, however that only gives access to the last version of Docker. There is an URL to each docker release binary, but AFAIK that does not mean the dependencies will be installed correctly.

**Comment by ahmetalpbalkan** [comment]
@stevenewey Just pushed the fix to production, the new extension version you'll be getting from now on should be `1.0.1508121604`. Thanks for the input and reporting the bug. Please try it out and let us know if you encounter any problems. :-) By the way, Docker 1.8.1 is out.

**Comment by stevenewey** [comment]
@ahmetalpbalkan That works, thanks for the fast turnaround, again!
