### ISSUE TITLE
Setting um VM with AZURE-CLI 

### ISSUE THREAD

**Issue by ArneCoder** [Azure/azure-docker-extension#57]
When i try to setup an new VM using "azure vm docker" the VM is created successful but when i visit the Azure Portal no Extensions are installed, neither i'am able to connect via docker client (getting i/o) timeout.

```
azure vm docker create geek-dock2 --ssh -l 'West US' -z "ExtraSmall" "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04-LTS-amd64-server-20140618.1-en-us-30GB" azureuser 'myPa$$w0rd' 
```

**Comment by ahmetalpbalkan** [comment]
Hi @ArneCoder, there's currently an issue in Azure CLI 0.9.9 which causes the extension to be not added to the VM: https://github.com/Azure/azure-xplat-cli/issues/2119

In the meanwhile, please consider downgrading your azure cli version or create a VM and install Docker manually: https://docs.docker.com/installation/ubuntulinux/

**Comment by ahmetalpbalkan** [comment]
@ArneCoder this bug should have been fixed in newer versions of azure-cli. Closing for now, please let us know if you run into any issues.
