### ISSUE TITLE
azure vm docker create yields devicemapper backend

### ISSUE THREAD

**Issue by spanditcaa** [Azure/azure-docker-extension#6]
I'm creating ubuntu 14.04.2 LTS vm's using the following syntax for the xplat cli.

````
azure vm docker create --ssh -l "West US" -n "dockerhost01" dockerhost01 "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_2_LTS-amd64-server-20150309-en-us-30GB" user pass --availability-set "dockerhost01-as" --virtual-network-name "docker-net" -b Subnet-1 --docker-cert-dir ./certs
````

The resulting docker instances use devicemapper as the storage backend, not aufs and as such are affected by this issue: https://github.com/docker/docker/issues/4036.  Below is the docker info from one of my deployed machines.  If I run the docker installation manually (https://github.com/Azure/azure-docker-extension/blob/master/scripts/install.sh#L65-L72) on a VM created from the same image, I do not have the same problem and the docker installation picks up aufs as expected.  Is the code in this repository the 'live' docker extension for azure, or is there some other problem ?  

Thanks.

docker info:
````
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-8:1-131207-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 725 kB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.16.0-31-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 1.639 GiB
Name: dockerhost01
ID: ....
Username: ....
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
````

**Comment by ahmetalpbalkan** [comment]
@spanditcaa Thanks, I will take a look into this. Meanwhile what is the version of azure CLI you have installed?

**Comment by spanditcaa** [comment]
0.8.16.  I'll update to .17 and let you know if that makes a difference.

**Comment by ahmetalpbalkan** [comment]
@spanditcaa I just used the same image [1] to create a new VM with this cmomand and it uses `aufs`.


> [1]: b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_2_LTS-amd64-server-20150309-en-us-30GB

**Comment by spanditcaa** [comment]
Yes - it looks like 0.8.17 did the trick.  Mine came out with ````aufs```` as well.  Thank you.
