### ISSUE TITLE
Change the way to install docker-engine

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-docker-extension#62]
https://github.com/Azure/azure-docker-extension/blob/master/pkg/driver/ubuntu_base.go#L10
I notice that, the extension uses the legacy way instead of the recommended one in docker's official document to install docker-engine.

Is it because the legacy way is more common for Ubuntu and other distros?

**Comment by ahmetalpbalkan** [comment]
@bingosummer Hmm, the apt repos of docker started around June and I have not looked at the installation instructions or came across any deprecation notices, yet. It appears like the installation instructions at https://docs.docker.com/engine/installation/ubuntulinux/ change even between ubuntu versions (not to mention that doesn't cover any other major linux distributions such as debian, fedora, centos).

To me it seems like `wget | sh` is working fine and I will sync with docker engine maintainers about plans to keep get.docker.com script around. If it is going to stick around longer, it makes sense to keep using it as we'll support more Linux images such as RHEL and the get.docker.com script painlessly covers all that already.

**Comment by bingosummer** [comment]
Thanks for your quick response. @ahmetalpbalkan 

However, if I want to replace https://apt.dockerproject.org/repo with a mirror URL to accelerate downloading and installing docker-engine, the `wget | sh` won't help.

**Comment by ahmetalpbalkan** [comment]
@bingosummer that's a valid argument but the extension does not offer a lot of customizations either. It is designed to handle the most common use cases. Users can do what the extensions do for them manually and maintain the docker engines on their VMs using CustomScriptExtension or various other ways.

**Comment by ahmetalpbalkan** [comment]
@bingosummer I asked about the get.docker.com script and it turns out the script will be eventually deprecated but not anytime soon.

I will keep this issue open as a reminder to fix it at some point.

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
