### ISSUE TITLE
[Question] About the best practice of publishing extensions

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-docker-extension#65]
Hi, I'd like to follow your maintainers guide to refine our extension publishing process of https://github.com/Azure/azure-linux-extensions.

My question is: Before you proceed to next slice, will you run all the tests to make sure the new release works as expected? What's the publish interval between each slice?

Thanks!

**Comment by ahmetalpbalkan** [comment]
@bingosummer right now I am manually testing and hoping to write an automation for that. It's a bit tough to automate as there are various distros (ubuntu1404/1504, coreos, rhel/centos) I need to test on. I usually publish the extension to my own subscription, create a VM of each distro in parallel on my terminal and add a complicated extension config that pretty much exercises all features. That about takes 10-20 minutes of mine unfortunately, however once I verify it all works, I rapidly push to next slices and to PROD within a few minutes.

**Comment by bingosummer** [comment]
Thanks @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
@bingosummer I just merged a bash script that does some fundamental integration tests for new versions of the extension on various distro images. It deploys the extension to VMs in parallel and exercises pretty much all features and checks if the VMs reach the goal state set by the extension configuration. I hope that helps.
