### ISSUE TITLE
Problem when publishing / question

### ISSUE THREAD

**Issue by colrack** [Azure/azure-docker-extension#70]
Hi

I've read docs at [Maintainers-Guide](https://github.com/Azure/azure-docker-extension/blob/master/doc/Maintainers-Guide.md) and I can successfully build and pack the extension with `make bundle `.
However when I `make publish`, something is failing.
I've changed in Makefile the `STGACCT` var with my storage account and `SUBS_ID` with my subscription id. When I run `make publish` I'm asked for the `accountkey`; I provide it and then I can see the blob is uploaded successfully in my storage account. Then I'm asked for `Path to Subscription Management Cert` and I provide it; however API call to `https://management.core.windows.net/SUBS_ID/services/extensions` (where SUBS_ID is my subscription id) is failing and returns a 403 response with this body:
```
<Error xmlns="http://schemas.microsoft.com/windowsazure"
       xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
    <Code>ForbiddenError</Code>
    <Message>This operation is not allowed for this subscription.</Message>
</Error>
```

I've also read [Handler Registration](https://github.com/Azure/azure-linux-extensions/blob/4fdf5492ed21a802f515a2ef3f62a1f6ab1f5931/docs/handler-registration.md#register-your-extension) and related docs and code at [azure-linux-extensions](https://github.com/Azure/azure-linux-extensions) but I'm encountering the same issue when publishing the sample extension: the operation seems to be not allowed for my subscription.

Am I missing something?
Am I supposed to register to some sort of service?
Where can I find docs about `https://management.core.windows.net/SUBS_ID/services/extensions` API? I can't find them on [Service Management REST API Reference](https://msdn.microsoft.com/en-us/library/azure/ee460799.aspx), can you point me to the right place?
Can anyone help?

Thanks!

**Comment by ahmetalpbalkan** [comment]
@colrack Hi, that document is meant only for Azure employees with extension publishing permissions. (in other words, you're not a maintainer :smile:). What do you need?

**Comment by colrack** [comment]
Hi

Thanks @ahmetalpbalkan 
I just want to hack something and publish my own extension for testing purpose, is this something possible? According to azure-linux-extensions docs seems to be possible. Maybe I've misunderstood and publishing extensions is something only internals can do? But I don't think so since `azure vm extension list-image-publishers` gives me a list with a lot of publishers

**Comment by ahmetalpbalkan** [comment]
@colrack No, it's not possible. `azure vm extension list-image-publishers` provides extension publishers as well as image publishers (that's why the list appears very long). If you run: 

```
$ azure config mode asm && azure vm extension list | grep -iv microsoft
data:    Publisher             Extension name   Description                Version
data:    --------------------  ---------------  -------------------------  -------
data:    AlertLogic.           AlertLogicLM     Alert Logic Log Manager    1.3
data:    AlertLogic.Extension  AlertLogicLM     Alert Logic Log Manager    1.9
data:    Chef.Bootstrap.Wi...  CentosChefCl...  Chef Extension that se...  11.14
data:    Chef.Bootstrap.Wi...  ChefClient       Chef Extension that se...  1210.12
data:    Chef.Bootstrap.Wi...  LinuxChefClient  Chef Extension that se...  1210.12
data:    CloudLinkEMC.Secu...  CloudLinkSec...  CloudLink SecureVM pro...  5.0
data:    CloudLinkEMC.Secu...  CloudLinkSec...  CloudLink SecureVM pro...  5.0
data:    Confer                ConferForAzure   Confer Advanced Threat...  1.0
data:    Datadog.Agent         DatadogLinux...  Datadog helps you moni...  0.4
data:    Datadog.Agent         DatadogWindo...  Datadog helps you moni...  0.5
data:    dynatrace.ruxit       ruxitAgentLinux  Ruxit Agent for Linux      1.81
data:    dynatrace.ruxit       ruxitAgentWi...  Ruxit Agent for Windows    1.81
data:    ESET                  FileSecurity     ESET File Security for...  6.2
data:    Gemalto.SafeNet.P...  ProtectVClie...  The ProtectV client en...  3.0
data:    Gemalto.SafeNet.P...  ProtectVClie...  The ProtectV client en...  3.0
data:    McAfee.EndpointSe...  McAfeeEndpoi...  McAfee Endpoint Protec...  6.0
data:    PuppetLabs            PuppetEnterp...  Puppet configuration r...  3.2
data:    Symantec              SymantecEndp...  Symantec Endpoint Prot...  12.1
data:    Test.TrendMicro.D...  TrendMicroDS...  Deep Security delivers...  9.6
data:    TrendMicro.DeepSe...  TrendMicroDSA    Deep Security delivers...  9.6
data:    TrendMicro.DeepSe...  TrendMicroDS...  Deep Security delivers...  9.6
data:    TrendMicro.Portal...  PortalProtec...  Trend Micro??PortalPro...  2.1
data:    Vormetric             VormetricTra...  Vormetric Transparent ...  5.2
info:    vm extension list command OK
```

you will see we only have a small number of external partners allowed to publish extensions. If you have an an ISV who can leverage extensions system to publish your software, feel free to contact us.
