### ISSUE TITLE
CentOS 7.1: Extension stuck in transitioning state

### ISSUE THREAD

**Issue by keyki** [Azure/azure-docker-extension#73]
The docker extension hangs in transitioning state on Centos 7.2. It was working a few weeks ago with 1.9.1, but now it tries to install 1.10.1. `yum install docker-engine` works, but reports a warning: `Delta RPMs disabled because /usr/bin/applydeltarpm not installed.` Full log is attached below.
Execution stops here: https://github.com/Azure/azure-docker-extension/blob/1f5b3a5defedb901fa2c48cea608b9da3f5ff7b6/op-enable.go#L64 (line 41 reached, but 71 never)

```
[root@cbdeployerVM Microsoft.Azure.Extensions.DockerExtension-1.1.1601140348]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

[root@cbdeployerVM Microsoft.Azure.Extensions.DockerExtension-1.1.1601140348]# uname -a
Linux cbdeployerVM 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
## /var/log/azure/Microsoft.Azure.Extensions.DockerExtension/1.1.1601140348/docker-extension.log
```
[DockerExtension] 2016/02/17 16:03:58 ----------------------------------------
[DockerExtension] 2016/02/17 16:03:58 Extension handler launch args: "/var/lib/waagent/Microsoft.Azure.Extensions.DockerExtension-1.1.1601140348/bin/docker-extension install"
[DockerExtension] 2016/02/17 16:03:58 seqnum: 0
[DockerExtension] 2016/02/17 16:03:58 Status 'transitioning' not reported for operation 'Install Docker' (by design)
[DockerExtension] 2016/02/17 16:03:58 distro info: CentOS 7.1.1503
[DockerExtension] 2016/02/17 16:03:58 using distro driver: driver.CentOSDriver
[DockerExtension] 2016/02/17 16:03:58 user: root uid:0 gid:0
[DockerExtension] 2016/02/17 16:03:58 env['PATH'] = /sbin:/usr/sbin:/bin:/usr/bin
[DockerExtension] 2016/02/17 16:03:58 + starting: 'install'
[DockerExtension] 2016/02/17 16:03:58 installing is deferred to the enable step to avoid timeouts.
[DockerExtension] 2016/02/17 16:03:58 - completed: 'install'
[DockerExtension] 2016/02/17 16:03:58 Status 'success' not reported for operation 'Install Docker' (by design)
[DockerExtension] 2016/02/17 16:03:58 Cleaned up .seqnum file.
[DockerExtension] 2016/02/17 16:04:03 ----------------------------------------
[DockerExtension] 2016/02/17 16:04:03 Extension handler launch args: "/var/lib/waagent/Microsoft.Azure.Extensions.DockerExtension-1.1.1601140348/bin/docker-extension enable"
[DockerExtension] 2016/02/17 16:04:03 seqnum: 0
[DockerExtension] 2016/02/17 16:04:03 distro info: CentOS 7.1.1503
[DockerExtension] 2016/02/17 16:04:03 using distro driver: driver.CentOSDriver
[DockerExtension] 2016/02/17 16:04:03 user: root uid:0 gid:0
[DockerExtension] 2016/02/17 16:04:03 env['PATH'] = /sbin:/usr/sbin:/bin:/usr/bin
[DockerExtension] 2016/02/17 16:04:03 + starting: 'enable'
[DockerExtension] 2016/02/17 16:04:03 ++ install docker
[executil] 2016/02/17 16:04:03 +++ invoke: /bin/sh [-c curl -sSL https://get.docker.com/ | sh]
+ sh -c 'sleep 3; yum -y -q install docker-engine'
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/docker-main-repo/packages/docker-engine-selinux-1.10.1-1.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Public key for docker-engine-selinux-1.10.1-1.el7.centos.noarch.rpm is not installed
Importing GPG key 0x2C52609D:
 Userid     : "Docker Release Tool (releasedocker) <docker@docker.com>"
 Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d
 From       : https://yum.dockerproject.org/gpg
```

## /var/log/azure/Microsoft.Azure.Extensions.DockerExtension/1.1.1601140348/CommandExecution.log
```
2016/02/17 16:03:58 Downloading plugin manifest: Microsoft.Azure.Extensions.DockerExtension from http://rdfepirv2am2prdstr02.blob.core.windows.net/708cdbbfb9ad4802ac80a012992930b1/Microsoft.Azure.Extensions_DockerExtension_europewest_manifest.xml
2016/02/17 16:03:58 Plugin server is: rdfepirv2am2prdstr02.blob.core.windows.net
2016/02/17 16:03:58 Bundle URI = http://rdfepirv2am2prdstr02.blob.core.windows.net/708cdbbfb9ad4802ac80a012992930b1/Microsoft.Azure.Extensions__DockerExtension__1.1.1601140348
2016/02/17 16:03:58 Plugin bundlehttp://rdfepirv2am2prdstr02.blob.core.windows.net/708cdbbfb9ad4802ac80a012992930b1/Microsoft.Azure.Extensions__DockerExtension__1.1.1601140348downloaded successfully length = 2531904
2016/02/17 16:03:58 Extracted http://rdfepirv2am2prdstr02.blob.core.windows.net/708cdbbfb9ad4802ac80a012992930b1/Microsoft.Azure.Extensions__DockerExtension__1.1.1601140348 to /var/lib/waagent/Microsoft.Azure.Extensions.DockerExtension-1.1.1601140348
2016/02/17 16:03:58 Found RuntimeSettings for Microsoft.Azure.Extensions.DockerExtension V 1.1.1601140348
2016/02/17 16:03:58 Spawned bin/docker-extension install PID 2238
2016/02/17 16:04:03 installCommand completed.
2016/02/17 16:04:03 Installation completed for Microsoft.Azure.Extensions.DockerExtension-1.1.1601140348
2016/02/17 16:04:03 Found RuntimeSettings for Microsoft.Azure.Extensions.DockerExtension V 1.1.1601140348
2016/02/17 16:04:03 Spawned scripts/run-in-background.sh enable PID 2241
2016/02/17 16:04:08 enableCommand completed.
2016/02/17 16:04:08 Enable completed for Microsoft.Azure.Extensions.DockerExtension-1.1.1601140348
2016/02/17 16:04:08 Processing completed for Microsoft.Azure.Extensions.DockerExtension-1.1.1601140348
2016/02/17 16:04:08 Finished processing ExtensionsConfig.xml
```

**Comment by ahmetalpbalkan** [comment]
@keyki Thanks for reporting this. It appears like it got stuck at `curl -sSL https://get.docker.com/ | sh` command installing the docker engine. Could you please try running the command manually (kill existing azure-docker-extension process if it’s still stuck)?

Also if you are using a particular Azure image, if you could give the full image name, I would love to try this as well.

**Comment by lalyos** [comment]
Actually we were ssh-d into the instance and could watch that it did finish.
`curl -sSL https://get.docker.com/ | sh` was calling up yum install, it did finish, but with the warning.

After docker 1.10.1 was installed, but the service wasn't started `service docker status` was reporting dead/kill.

We were using `OpenLogic: CentOS:7.1:latest` as base. But actually you can try the full RMTemplate:
Click here: <a href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fsequenceiq%2Fazure-cbd-quickstart%2Fmaster%2Fazuredeploy.json">  ![deploy on azure](http://azuredeploy.net/deploybutton.png) </a>

From our [github repo](https://github.com/sequenceiq/azure-cbd-quickstart)

**Comment by ahmetalpbalkan** [comment]
@lalyos I see that you're using both CustomScriptExtension and DockerExtension (and both of these are installing stuff with `yum`) I'm not super familiar with yum, but I feel like if you issue two install commands, one might actually fail.

So using `dependsOn` property in the template, I encourage you to wait for one extension to finish and start another. By doing that for instance, you can first install DockerExtension, wait for it to complete (by using `"dependsOn" : "[name-of-docker-extension-resource]"` and start running the custom script.

**Comment by lalyos** [comment]
@ahmetalpbalkan 
We do exactly what you described our custom script waits for decker extension to finish:
https://github.com/sequenceiq/azure-cbd-quickstart/blob/centos/azuredeploy.json#L230-L232

we have watched the instance, and in fact our custom script extension didnt even started, as the Docker extension was in `trasitioning` state. So the custom script had no infuence at all.

You can try it yourself and start an instance: Click here: <a href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fsequenceiq%2Fazure-cbd-quickstart%2Fcentos%2Fazuredeploy.json">  ![deploy on azure](http://azuredeploy.net/deploybutton.png) </a>

I guess you guys have some azure accounts to play with ;)

**Comment by ahmetalpbalkan** [comment]
@lalyos I just reproed the stopped daemon behavior after installing. I think we should report this to Docker as the install script is expected to start the docker-engine. I am going to open an issue now.

**Comment by ahmetalpbalkan** [comment]
@lalyos https://github.com/docker/docker/issues/20409 please feel free to subscribe to the issue.

**Comment by lalyos** [comment]
Sure, please put an issue reference here, i might try to collect more information.

Btw it would be nice to have docker version as a configuration parameter ... It was workinh fine with 1.9.1. But the `curl -sSL https://get.docker.com/ | sh` always tries to install the latest ...

**Comment by lalyos** [comment]
I have rerun the script with and added `set -x` so more output (see below)
But it seems like that script does what it should and _installs_ docker, and exists with 0.
So i think the question is why the enable_operation got stuck at: [Line 64](https://github.com/Azure/azure-docker-extension/blob/1f5b3a5defedb901fa2c48cea608b9da3f5ff7b6/op-enable.go#L64)


```
+ url=https://get.docker.com
+ apt_url=https://apt.dockerproject.org
+ yum_url=https://yum.dockerproject.org
+ gpg_fingerprint=58118E89F3A912897C070ADBF76221572C52609D
+ do_install
+ case "$(uname -m)" in
++ uname -m
+ command_exists docker
+ command -v docker
++ id -un
+ user=root
+ sh_c='sh -c'
+ '[' root '!=' root ']'
+ curl=
+ command_exists curl
+ command -v curl
+ curl='curl -sSL'
+ '[' -z '' ']'
+ repo=main
+ '[' https://test.docker.com/ = https://get.docker.com ']'
+ '[' https://experimental.docker.com/ = https://get.docker.com ']'
+ lsb_dist=
+ dist_version=
+ command_exists lsb_release
+ command -v lsb_release
+ '[' -z '' ']'
+ '[' -r /etc/lsb-release ']'
+ '[' -z '' ']'
+ '[' -r /etc/debian_version ']'
+ '[' -z '' ']'
+ '[' -r /etc/fedora-release ']'
+ '[' -z '' ']'
+ '[' -r /etc/oracle-release ']'
+ '[' -z '' ']'
+ '[' -r /etc/centos-release ']'
+ lsb_dist=centos
+ '[' -z centos ']'
++ tr '[:upper:]' '[:lower:]'
++ echo centos
+ lsb_dist=centos
+ case "$lsb_dist" in
++ rpm -q --whatprovides redhat-release --queryformat '%{VERSION}\n'
++ sed 's/\/.*//'
++ sed 's/\..*//'
++ sed 's/Server*//'
+ dist_version=7
+ check_forked
+ command_exists lsb_release
+ command -v lsb_release
+ case "$lsb_dist" in
+ sh -c 'cat >/etc/yum.repos.d/docker-main.repo'
+ '[' centos = fedora ']'
+ set -x
+ sh -c 'sleep 3; yum -y -q install docker-engine'
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/docker-main-repo/packages/docker-engine-1.10.1-1.el7.centos.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Public key for docker-engine-1.10.1-1.el7.centos.x86_64.rpm is not installed
Importing GPG key 0x2C52609D:
 Userid     : "Docker Release Tool (releasedocker) <docker@docker.com>"
 Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d
 From       : https://yum.dockerproject.org/gpg
+ echo_docker_as_nonroot
+ command_exists docker
+ command -v docker
+ '[' -e /var/run/docker.sock ']'
+ your_user=your-user
+ '[' root '!=' root ']'
+ cat

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

+ exit 0
```

**Comment by ahmetalpbalkan** [comment]
@lalyos get.docker.com script should also be starting docker, that's not doing it.

Based on `docker-extension.log`, the extension kicks off the script (and if your log snippet is complete), it stops getting any further output right here:

```
[executil] 2016/02/17 16:04:03 +++ invoke: /bin/sh [-c curl -sSL https://get.docker.com/ | sh]
+ sh -c 'sleep 3; yum -y -q install docker-engine'
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/docker-main-repo/packages/docker-engine-selinux-1.10.1-1.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Public key for docker-engine-selinux-1.10.1-1.el7.centos.noarch.rpm is not installed
Importing GPG key 0x2C52609D:
 Userid     : "Docker Release Tool (releasedocker) <docker@docker.com>"
 Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d
 From       : https://yum.dockerproject.org/gpg
```

**Comment by ahmetalpbalkan** [comment]
> Btw it would be nice to have docker version as a configuration parameter

@lalyos currently we think it's better to install the latest version (mostly because get.docker.com script does not take a version number). However we are eventually hoping to get rid of get.docker.com script as docker tends to break every now and then. See: #62.

In this case, the breaking change probably has occurred in the installation script (not actually in the docker-engine) so the docker engine version might not have anything to do with it. I'd say let’s stay tuned on the issue here: https://github.com/docker/docker/issues/20409 I’m curious to find out why is it not starting the engine.

**Comment by lalyos** [comment]
Hmm I'm not sure about that `get.docker.com` should start the docker daemon.
The script originally is stored in [github](https://github.com/docker/docker/blob/master/hack/install.sh)

You can see on [line 443](https://github.com/docker/docker/blob/master/hack/install.sh#L443):
```
yum -y -q install docker-engine
# closing the if
echo_docker_as_nonroot
exit 0
```

So the last real step in "get.docker.com" is `yum install`. But I dont think that yum install itself should start the daemon, as the official documentation describs it as 2 separate steps:

> ...
> Step-4: Install the Docker package.
>
>  `$ sudo yum install docker-engine`
> 
> Step-5: Start the Docker daemon.
>
>  `$ sudo service docker start`

Having said that, we should still see at the end of the `docker-extension.log` the `echo_docker_as_nonroot` output, which starts like:
```
If you would like to use Docker as a non-root user, you should now consider
```
Thats missing ...

But when i manually run the `get.docker.com` script it did run until `echo_docker_as_nonroot`.

**Comment by lalyos** [comment]
I will try to re-run the whole process a couple of more times, to see if this "stucking" happens consistently.

**Comment by ahmetalpbalkan** [comment]
@lalyos thanks, I think there has been a change to the scripts lately because CentOS 7.1 image is one of our integration test images (in fact now that as of today we have RHEL on Azure, I’ll add that to our list too). I will re-run integration tests to see if there is anything funny going on regarding this change.

**Comment by ahmetalpbalkan** [comment]
@lalyos indeed there has been a change to get.docker.com script impacting CentOS 7.1, our integration test has just failed with this latest docker version. I will be debugging this pushing a fix soon. Please stay tuned for updates.

**Comment by ahmetalpbalkan** [comment]
@lalyos Hello, I have been debugging for a while now. Apparently when the extension is invoked in headless mode by Azure Linux Agent, it installs docker and then mysteriously crashes. This only happens for the first time and when I reboot the VM, the extension works just fine.

I could not find any failures or crashes in the journal yet, I will be investigating more to collect more diagnostics about what might be happening.

**Comment by knom** [comment]
Hi guys,
I'm having the same issue, on CentOS 7.1.
No custom script extension.. just the Docker extension!

What's the state?

**Comment by ahmetalpbalkan** [comment]
I believe I found the issue here, it appears like some signaling behavior between nohup and log redirection is causing some crash. The version with the fix is currently being replicated (may take 1-2 days).

**Comment by ahmetalpbalkan** [comment]
Update: I think it'll be at least 4-5 days to get the fix to production under the current load we're experiencing in the replication queue internally. Please try some other non-CentOS image in the meanwhile to work your way around the problem.

**Comment by ahmetalpbalkan** [comment]
@lalyos @keyki Hi folks, this should be fixed now. Please try out again, you should be getting version `1.1.1602270800` of the extension and according to our tests, this new version succeeds fine. If you're curious what the issue was, you can look at #77.

**Comment by lalyos** [comment]
Thanks @ahmetalpbalkan ! I confirm it doesn't hangs anymore.

So it gets further, but the whole deployment reported as "failed" altough all operations, excepth the last one, which is "write" operation on "Template" resource.

![screen shot 2016-02-29 at 7 05 32 pm](https://cloud.githubusercontent.com/assets/464122/13403878/7b106360-df17-11e5-993c-8ff7cef749ff.png)
So its now related to: Azure/azure-quickstart-templates/issues/1294

**Comment by ahmetalpbalkan** [comment]
@lalyos alright, it seems unrelated to azure-docker-extension. Closing this issue. Thanks for reporting and sorry for the inconvenience.
