### ISSUE TITLE
docker-compose.yml is overridden every reboot

### ISSUE THREAD

**Issue by dmoreno** [Azure/azure-docker-extension#78]
I'm using Azure Virtual Machine with preconfigured Docker and I see it is using azure-docker extension.

I need configure /etc/docker/compose/docker-compose.yml for passing some parameters to jenkins container. But with every reboot that changes in docker-compose.yml disapears.

Is this the normal behavior?

I see the same configuration in /var/lib/waagent/Microsoft.Azure.Extensions.DockerExtension-1.1.1601140348/config/0.settings but I don't know if this is the place to make this configuration.

What is the best way to configure docker-compose.yml with custom parameters?

**Comment by ahmetalpbalkan** [comment]
@dmoreno it's expected behavior. This extension should be used for bootstrapping an initial set of containers (an immutable set, to be precise) such as monitoring, cluster management, security etc.

Once the extension is deployed you should use docker client or docker-compose directly against your docker daemon to launch/manage containers.

**Comment by dmoreno** [comment]
Thanks for the answer, @ahmetalpbalkan. I got your point.

This azure-docker-extension is used in the official Jenkins Virtual Machine provided by Docker in Azure Marketplace to launch the Jenkins container with a  fixed configuration. And with this behavior is very difficult to modify the running container, for example, to attach new volumes.

In your opinion, is this use of the extension correct?

**Comment by ahmetalpbalkan** [comment]
@dmoreno 

`<personal opinion>` 
I think having Container Apps on Azure Marketplace was a bad idea. (1) We are not actually letting people configure anything useful. (2) We're not teaching people docker, we just do something for them. (3) It runs one container per VM = pointless. (4) It often produces unseeable results, such as starting Redis container that's closed to public internet has no visible effect, so users feel like _"so what happened now"_.

I can continue keep going. So please don't use Container Apps section in Azure Marketplace if you actually know what you're doing. Running a jenkins container from docker CLI is very simple ([docs](https://hub.docker.com/r/library/jenkins)) and the Marketplace experience just complicates things and adds no real value.
`</personal opinion>`

**Comment by dmoreno** [comment]
Thanks for your opinion, @ahmetalpbalkan. I totally agree with you.

I think "Docker on Ubuntu Server" Virtual Machine in Azure catalog (provided by Canonical + Microsoft) seems more useful if you know what you are doing. It uses azure-docker-extension too.
