### ISSUE TITLE
Using protected environment in container environment

### ISSUE THREAD

**Issue by tmds** [Azure/azure-docker-extension#79]
I am trying to figure out how to use environment from protected in a container environment.

From README.md, I think it should be done like this:

        "cache" : {
            "image" : "memcached",
            "ports" : ["11211:11211"],
            "environment": [ "SECRET_ENV=${SECRET_ENV}" ]
        }

Looking at azure-docker-extension/integration-test/extensionconfig/public.json, makes me think this is the right approach:

        "cache" : {
            "image" : "memcached",
            "ports" : ["11211:11211"],
            "environment": [ "SECRET_ENV" ]
        }

How can the protected environment be used in the container environment?
Perhaps the readme can be updated to make this more clear?

**Comment by ahmetalpbalkan** [comment]
@tmds the integration test actually gives a good idea, that's how public.json should be like. Then you need to specify the value of SECRET_ENV in protected.json: https://github.com/Azure/azure-docker-extension/blob/master/integration-test/extensionconfig/protected.json in ARM templates this JSON file goes under "protectedSettings" key. It is documented under _1.2. Protected Configuration Keys_ in the README:

https://github.com/Azure/azure-docker-extension#12-protected-configuration-keys

**Comment by tmds** [comment]
The documentation says:

> compose: (optional, JSON object) the compose.yml file to be used, converted to JSON. If you are considering to embed secrets as environment variables in this section, please see the "environment" key described below.

> environment: (optional, JSON object) Key value pairs to store environment variables to be passed to docker-compose securely. By using this, you can avoid embedding secrets in the unencrypted "compose" section.

The compose file reference says:

> You can use environment variables in configuration values with a Bash-like ${VARIABLE} syntax

When I read this, my assumption is [ "SECRET_ENV=${SECRET_ENV}" ] will set the variable in the compose section, passed from protected as an environment variable to compose.

Is it possible to set variables directly in the compose container environment, without using protected environment variables?

**Comment by ahmetalpbalkan** [comment]
@tmds ah maybe the `SOME_NAME=${SOME_OTHER_NAME}` syntax might be a way to rename environment keys. Like maybe in protected session you specify PASSWORD and in compose.yml, use it as MYSQL_PASSWORD and so forth.

If you don't want to rename the keys, in compose.yml you can just say `environment: [ "SECRET_ENV"] ` and it will use the SECRET_ENV var directly (you don't need the `=${...}`).

Basically what we do is, we read the environment variables and their values specified in protected sessions, pass that to `docker-compose` process. That's pretty much it. Depending on the .yml you specify, they'll get used or discarded.

So if you have a public configuration with "environment" key like:
![image](https://cloud.githubusercontent.com/assets/159209/14359849/54d15778-fca8-11e5-8b04-35b87b8985a6.png)

and protected configuration with contents like:
![image](https://cloud.githubusercontent.com/assets/159209/14359867/66644220-fca8-11e5-91be-48f1d24f09c6.png)

your container will indeed get SECRET_ENV value. Based on your needs, you can rename these fields.

**Comment by tmds** [comment]
Indeed, both syntaxes should work. From the compose file reference:

> Environment variables with only a key are resolved to their values on the machine Compose is running on, which can be helpful for secret or host-specific values.

**Comment by ahmetalpbalkan** [comment]
@tmds does that resolve the issue for you?

**Comment by tmds** [comment]
I will try some of these things out tomorrow and if everything works fine (which I expect to be the case), I'll close the issue.

**Comment by tmds** [comment]
@ahmetalpbalkan Both syntaxes work fine. Thanks for your help.

**Comment by ahmetalpbalkan** [comment]
@tmds great to hear, please let us know if you run into any more questions.
