### ISSUE TITLE
failed executing docker-compose

### ISSUE THREAD

**Issue by tmds** [Azure/azure-docker-extension#80]
I am trying to deploy an ARM template which worked before, but now I get an error message:
```
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'DockerExtension'. Error message: \"Enable Docker failed: ERROR: 'compose up' failed: executing /usr/local/bin/docker-compose [-p compose -f /etc/docker/compose/docker-compose.yml up -d] failed: exit status 1\"."
      }
    ]
  }
}
```

I had a look on the virtual machine, which is using:
```
root@MyDockerVM:/etc/docker/compose# docker --version
Docker version 1.11.0, build 4dc5990
root@MyDockerVM:/etc/docker/compose# docker-compose version
docker-compose version: 1.5.1
docker-py version: 1.5.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

When I try to launch `docker-compose up`, docker-compose is unable to pull my image. However, when I try to pull the image with `docker`, it works fine.

Debugging this further made me learn that docker-compose wasn't working because there was no `email `property in `~/.docker/config.json`.

This property should have been set during the deployment, which executes the `docker login`.

Manually executing the command shows this nice message:

`Warning: '-e' is deprecated, it will be removed soon. See usage.`

And it doesn't write an email to the config.json, which breaks docker-compose...

**Comment by ahmetalpbalkan** [comment]
That's just a warning though. It doesn't seem like it is the error. Can you please look at the log files mentioned in the README?

**Comment by tmds** [comment]
@ahmetalpbalkan the docker 1.7 login command doesn't write the email field in the config.json, and docker-compose 1.5.1 doesn't pull images without the email field.

**Comment by tmds** [comment]
This error is occurring now because docker 1.11 was just released.
This extension fixes docker-compose to [1.5.1](https://github.com/Azure/azure-docker-extension/blob/be85902b29ada852968ad02a157d12ef0ad4d733/op-enable.go#L25).
It always gets the latest version of docker from [get.docker.com](https://github.com/Azure/azure-docker-extension/blob/be85902b29ada852968ad02a157d12ef0ad4d733/pkg/driver/ubuntu_base.go#L10).
These versions are not compatible because [the email field was removed](https://github.com/docker/docker/pull/20565).

**Comment by ahmetalpbalkan** [comment]
@tmds ah I see now, it is docker-compose that is not compatible with the missing email field. (Please correct me if that is not the case.) Thanks for reporting, I am taking a look.

**Comment by tmds** [comment]
Yes, that's the issue.

**Comment by ahmetalpbalkan** [comment]
@tmds I'm seeing a bit different issue:

```
$ tail -f /var/log/azure-docker-extension-enable.log
...
[executil] 2016/04/14 20:16:50 +++ invoke: /usr/local/bin/docker-compose [-p compose -f /etc/docker/compose/docker-compose.yml up -d]
The DOCKER_CLIENT_TIMEOUT environment variable is deprecated. Please use COMPOSE_HTTP_TIMEOUT instead.
Pulling web (nginx:latest)...
Creating compose_web_1
rpc error: code = 2 desc = "containerd: container did not start before the specified timeout"
[executil] 2016/04/14 20:17:59 --- invoke end
```

when I ssh in `sudo -s` and _manually_ run `docker-compose -p compose -f /etc/docker/compose/docker-compose.yml up -d` everything works fine.

There's no indication that it is an email field issue. Can you please look at your log file I used above?

**Comment by ahmetalpbalkan** [comment]
@tmds I opened an issue about the error I'm getting: https://github.com/docker/docker/issues/22053

Unfortunately I don't think we can bump `docker-compose` version very straightforwardly. We support stable feed of CoreOS (docker-engine 1.9.1) and `docker-compose@1.7.0` requires docker-engine 1.10.0 or later.

**Comment by ahmetalpbalkan** [comment]
@tmds I just ran our tests against Ubuntu 14.04/15.10 and Centos 7.1 images running docker-engine 1.11.0 and docker-compose1.5, it just worked fine with unauthenticated Docker Hub images. 

I appreciate if you could provide some logs and how your extension configuration looks like.

**Comment by ryanreich** [comment]
I was just about to open a new issue on what appears to be exactly this, saying that it is clearly an instance of https://github.com/docker/compose/issues/1622.  I solved it by manually upgrading `docker-compose` to 1.7.0, but I can't do that in my ARM template...

**Comment by ahmetalpbalkan** [comment]
@ryanreich can you please send the error from your `/var/log/azure-docker-extension-enable.log`?

**Comment by ryanreich** [comment]
Well, I don't have that exact file, but here is the post-install portion of `/var/log/azure/Microsoft.Azure.Extensions.DockerExtension/1.0.1512030601/docker-extension.log`:

```
[DockerExtension] 2016/04/14 21:50:06 ++ login docker registry
[executil] 2016/04/14 21:50:06 +++ invoke: docker [login --email=********@gmail.com --username=******** --password=********]
Warning: '--email' is deprecated, it will be removed soon. See usage.
Login Succeeded
[executil] 2016/04/14 21:50:08 --- invoke end
[DockerExtension] 2016/04/14 21:50:08 -- login docker registry
[DockerExtension] 2016/04/14 21:50:08 ++ compose up
[DockerExtension] 2016/04/14 21:50:08 Using compose yaml:>>>>>
strato:
  command: strato-dev 1 1
  container_name: strato
  domainname: centralus.cloudapp.azure.com
  hostname: ryantest
  image: blockapps/strato:v1.1
  ports:
  - 80:80
  - 30303:30303
  - 30303:30303/udp
  restart: always

<<<<<
[executil] 2016/04/14 21:50:08 +++ invoke: /usr/local/bin/docker-compose [-p compose -f /etc/docker/compose/docker-compose.yml up -d]
The DOCKER_CLIENT_TIMEOUT environment variable is deprecated. Please use COMPOSE_HTTP_TIMEOUT instead.
Pulling strato (blockapps/strato:v1.1)...
Error: image blockapps/strato not found
[executil] 2016/04/14 21:50:10 --- invoke end
[DockerExtension] 2016/04/14 21:50:10 ERROR: 'compose up' failed: executing /usr/local/bin/docker-compose [-p compose -f /etc/docker/compose/docker-compose.yml up -d] failed: exit status 1
[DockerExtension] 2016/04/14 21:50:10 Cleaned up .seqnum file.
[DockerExtension] 2016/04/14 21:50:10 Exiting with code 1.
```

**Comment by ahmetalpbalkan** [comment]
@ryanreich it looks like you're using v1.0 of the extension, I strongly recommend upgrading to v1.1 if you could. Other than that `image [...] not found` issue appears to be the compose issue you linked above.

As I mentioned earlier in the thread, if we update to docker-compose 1.7.0 we will not be able to support latest CoreOS stable version (which has a significant use).

Do you think if `docker-compose 1.6.0` works fine with this or does it have to be `1.7.0`?

**Comment by ryanreich** [comment]
I will try the changes you suggest -- I only put '1.0' in there because the template has been using it for a while without issue, so I thought it was a good way to roll back to a successful past.

I only chose 1.7.0 because it was most recent; I'll bisect.

**Comment by ahmetalpbalkan** [comment]
@ryanreich if you have a template I suggest using the `"autoUpgradeMinorVersion": true,` option. [[example](https://github.com/Azure/azure-docker-extension#3-using-docker-extension-in-arm-templates)]

**Comment by ryanreich** [comment]
Ah, yes.  I actually did set that (blindly, because it was in the suggested syntax in the README :) ) but since I've been trying to find a minimal test, I was also deploying this on the command line using `azure vm extension set`, and put '1.0' explicitly there.

**Comment by ahmetalpbalkan** [comment]
@ryanreich Hmm in that case it looks like we are lacking a feature that could set autoUpgradeMinorVersion. (in ASM mode 1.* used to do that) I'll open an issue for our CLI team.

In the meanwhile, the docker-compose issue you linked seems like it is a bit old. If you could downgrade to 1.6 then 1.5.1 and each time run `docker-compose up` and see where it breaks, that would be great.

**Comment by ryanreich** [comment]
I'm on it.  This is fairly important to us.

**Comment by ahmetalpbalkan** [comment]
@ryanreich I'm not surprised. Docker is breaking down third time in a row with these releases.

**Comment by ryanreich** [comment]
So first of all, a partial update using version 1.1.  My log file (now called `/var/log/azure/Microsoft.Azure.Extensions.DockerExtension/1.1.1602270800/docker-extension.log`) now looks like this:

```
[DockerExtension] 2016/04/14 22:33:22 ++ login docker registry
[DockerExtension] 2016/04/14 22:33:24 -- login docker registry
[DockerExtension] 2016/04/14 22:33:24 ++ compose up
[DockerExtension] 2016/04/14 22:33:24 Using compose yaml:>>>>>
strato:
  command: strato-dev 1 1
  container_name: strato
  domainname: centralus.cloudapp.azure.com
  hostname: ryantest
  image: blockapps/strato:v1.1
  ports:
  - 80:80
  - 30303:30303
  - 30303:30303/udp
  restart: always

<<<<<
[executil] 2016/04/14 22:33:24 +++ invoke: /usr/local/bin/docker-compose [-p compose -f /etc/docker/compose/docker-compose.yml up -d]
The DOCKER_CLIENT_TIMEOUT environment variable is deprecated. Please use COMPOSE_HTTP_TIMEOUT instead.
Pulling strato (blockapps/strato:v1.1)...
Error: image blockapps/strato not found
[executil] 2016/04/14 22:33:25 --- invoke end
[DockerExtension] 2016/04/14 22:33:25 ERROR: 'compose up' failed: executing /usr/local/bin/docker-compose [-p compose -f /etc/docker/compose/docker-compose.yml up -d] failed: exit status 1
[DockerExtension] 2016/04/14 22:33:25 Cleaned up .seqnum file.
[DockerExtension] 2016/04/14 22:33:25 Exiting with code 1.
```
I'm a little unclear why the `docker login` portion was so brief, but perhaps that's for security (oh yes, there was a changelog about that in the README).  So it's the same business with the newer version, if that were ever in doubt.

**Comment by ryanreich** [comment]
And the results for `docker-compose`: version `1.6.0` works, but no `1.5` version works.

**Comment by ahmetalpbalkan** [comment]
@ryanreich it looks like `docker-compose v1.6.2` works with `docker-engine 1.9.1+`. In this case CoreOS stable would work fine. I am now making the change. I hope we will have a fix in a few hours.

**Comment by ryanreich** [comment]
Good news!

**Comment by tmds** [comment]
@ahmetalpbalkan this is a login issue, so you need to use a private repo otherwise the bug doesn't occur.

**Comment by ahmetalpbalkan** [comment]
@tmds That explains why our tests have missed that.

**Comment by marrobi** [comment]
Similar issue here, on Ubunto 15.10. Compose files stopped working, complaints about TLS settings. Updated to Compose 1.7 in a startup script extension:

#install latest version of compose 
curl -L https://github.com/docker/compose/releases/download/1.7.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

Seems to work now...

**Comment by ahmetalpbalkan** [comment]
Hi folks, it looks like our extension package replication system is running late today. I will update again when the fix makes it to Production.

**Comment by ahmetalpbalkan** [comment]
Hi folks, I just merged the fix bumping up docker-compose to v1.6.2 (#81) and published the new version of DockerExtension `v1.1.1604142300`.

It is currently being replicated to Azure regions, I am hoping it will be available in all regions later today. The newly created virtual machines should be picking up this version by default.

Please try it out (make sure that specific version lands to your Virtual Machine) and let us know if the issue still persists.

**Comment by ryanreich** [comment]
Seems to work.

**Comment by ahmetalpbalkan** [comment]
@ryanreich Thanks for confirming. Closing the issue.

**Comment by tmds** [comment]
I've switched to the CoreOS image. I am not a fan of the "download latest from get.docker.com" approach used for CentOS and Ubuntu. Upvoted https://github.com/Azure/azure-docker-extension/issues/74.
Thanks for fixing @ahmetalpbalkan.
