### ISSUE TITLE
Support dynamic compose definition via extension configuration updates

### ISSUE THREAD

**Issue by tmds** [Azure/azure-docker-extension#82]
I tried redeploying an ARM template specifying a different "image" in the docker extension. The deployment finishes with a success status. The old image is is still running after the deployment. My expectation was that the new image would be used.

**Comment by tmds** [comment]
Some more info:
- when I retrieve the resource description after the deployment, it shows the new image name (not the old image, which is still running)
- when I manually restart the vmss, I get the new image

**Comment by ahmetalpbalkan** [comment]
@tmds I'm assuming you're referring to a different docker-compose configuration not being effective.

Please don't use the docker-extension to run a dynamic set of containers. Its compose functionality is meant for running a static set of containers, mostly for:

- monitoring containers
- security containers
- agent to bootstrap clusters (see swarm template in azure-quickstart-templates)

We do not support dynamically changing the compose file for several reasons. Most important one is, it is hard to define the semantics around the compose.yml file when you do a `docker-compose up`. Let's say you had template v1 started containers {A,B,C} and now you updated your template to run containers {A,B,D}. Does this mean you want {A,B,C,D} running simultaneously, or {A,B,D} and {C} is deleted? 

Second most important one is, people are trying to use Extension as a dynamic container orchestrator more and more, they are redeploying ARM templates for VMs to update the containers etc. It is simply not meant for that and extension channel is a low latency channel. (1-2 minutes) If you really need to update your set of dynamic containers, I suggest using a proper container orchestrator, or enabling remote API access on your docker engine and using docker CLI to accomplish that task.

Does this help?

**Comment by tmds** [comment]
I understand the difference in use-cases.

Still I think it makes sense to run 'docker-compose up' on a redeploy. Docker-compose itself is also limited to static use-cases. The most important case being: updating the version of an image.

The current behavior is ambiguous:
The extension reports success on a redeploy with a changed configuration, but it doesn't apply it.
The new configuration is actually written and it is applied upon reboot.

**Comment by ahmetalpbalkan** [comment]
@tmds Fair point, I think it would be better to document this clearer than defining a new behavior around it.

**Comment by tmds** [comment]
I think it would be better to run 'docker-compose up' on redeploy which will enrich the static use-cases and get rid of the ambiguous behavior.

**Comment by ahmetalpbalkan** [comment]
I tend to prefer actually not writing to the /etc/docker/docker-compose.yml if it exists (so that on the next reboot, it will not be effective). It is easier to control more strict definition and extend the contract in the future. In any case I should probably think about this a bit. Essentially, making this use case available may just end up creating a monster and more people may actually start using this as a means of container orchestration. If there is anything blocking you in the meanwhile, please let me know.

**Comment by tmds** [comment]
I don't see this monster, nor do I understand what drawbacks there could be from running 'docker-compose up'.
I am only one user. For my use case: one container, one image which needs to be updated from one version to another, I will have to do a setup with an orchestrator where docker-compose level setup would have sufficed.

**Comment by tmds** [comment]
@ahmetalpbalkan give it some thought. I understand your point from an architecture perspective. Likewise, when I look from the architecture perspective, for some setups, the 'docker-compose up' is good enough.
Most documentation and examples out there (including the azure templates and the readme of this repo) show 'functional' containers. What you wrote earlier about the intended use-cases of the compose section came came as a surprise to me.

**Comment by ahmetalpbalkan** [comment]
@tmds I just came back to this issue. From my experimentation, it looks like the feature you asked is already there. I just used azure CLI command:

    azure vm extension set <resource-group> <vm> DockerExtension Microsoft.Azure.Extensions '1.*' --public-config '{"compose":{"sleep1":{"image":"busybox", "command":["sleep","999"], "restart":"always"}}}'

and added new service such as:

    '{"compose":{"sleep2":{"image":"busybox", "command":["sleep","999"], "restart":"always"}}}'

and updated sleep1 commandline args:

    '{"compose":{"sleep1":{"image":"busybox", "command":["sleep","888"], "restart":"always"}}}'

and it all worked.

Are you trying with ARM templates and seeing that `/etc/docker/compose/docker-compose.yml` is not getting updated?

**Comment by tmds** [comment]
@ahmetalpbalkan I am sure the feature did not work when I reported it, some things must have changed. Are you using Ubuntu?

Will this be a feature? E.g. will it be documented and tested it doesn't break with new versions of the various components (OS, docker, docker compose, etc.)? Thanks.

**Comment by ahmetalpbalkan** [comment]
@tmds As far as I can tell, we have not changed anything regarding this. As I said before, I am most probably going to say no to advertising this feature as the use case for having dynamic set of containers updated through Docker Extension is not a use case we want to have. That is something container orchestrators are already addressing.

Docker Extension is just a simple tool to bootstrap base containers such as orchestrator agents, monitoring and security software. Regarding the breaking behavior, we are constantly getting broken by Docker releases very consistently for the past few releases and we acted fast to get fixes out there quickly.

Regarding this issue, I suggest you to try reproducing the issue. Perhaps there is something with the Azure Resource Manager templates that are not working correctly or some combination of that and the Docker Extension, we definitely would like to address those.

**Comment by tmds** [comment]
@ahmetalpbalkan due to this issue I've moved to Rancher to orchestrate the image upgrade. This has issues of it's own since as Rancher is also picky about the docker version. I've stopped investigating because my current setup is good enough.

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
