### ISSUE TITLE
Docker Extension doesn't work

### ISSUE THREAD

**Issue by giovannifl** [Azure/azure-docker-extension#83]
Since today,
I'm experiencing following issue when Docker Extension is used:

[ERROR] New-AzureRmResourceGroupDeployment : 3:13:27 PM - VM has reported a failure 
[ERROR] when processing extension 'DockerExtension'. Error message: "Enable Docker 
[ERROR] failed: ERROR: executing /bin/sh [-c curl -sSL https://get.docker.com/ | sh] 
[ERROR] failed: exit status 1".

May be there are some issue while trying to download Docker bits ?

Thanks

**Comment by giovannifl** [comment]
It seems this issue is related to CenOs 7.2.
No issues with Ubuntu 16.04

**Comment by giovannifl** [comment]
After some diggings, it seems CentOs has updated a package and OpenLogic repository is still point to the old one.
![01](https://cloud.githubusercontent.com/assets/19493042/15441723/8a0fd486-1eaa-11e6-970f-dd7b758c1be9.JPG)
![02](https://cloud.githubusercontent.com/assets/19493042/15441724/8a1200ee-1eaa-11e6-9cc9-52f6a3c0b146.JPG)
![03](https://cloud.githubusercontent.com/assets/19493042/15441725/8a12b2dc-1eaa-11e6-9889-54b13e429558.JPG)

**Comment by giovannifl** [comment]
Issue still available

**Comment by szarkos** [comment]
Can you check again, this should be resolved now.

**Comment by giovannifl** [comment]
![04](https://cloud.githubusercontent.com/assets/19493042/15511182/823bfc8e-21a8-11e6-8b3b-f90c5ded1759.JPG)

Confirmed. Docker extension on CentOs now work again.
Packages have been updated
