### ISSUE TITLE
Documentation doesn’t specify the name of the created compose project

### ISSUE THREAD

**Issue by alinamstanciu** [Azure/azure-docker-extension#85]
The documentation doesn’t specify what the name of the created compose project is.

**Comment by ahmetalpbalkan** [comment]
@alinamstanciu you are right, the compose containers we create will have project prefix `compose_` as the .yml file we generate resides in `/etc/docker/compose` directory.

Would you like it to be documented (in other words, are you planning to rely on it) or would you like an ability to configure it?

**Comment by vishwam** [comment]
I'd prefer the project name to be configurable.

**Comment by ahmetalpbalkan** [comment]
@vishwam Please look at the newly added `compose-environment` key in the README. specifying `DOCKER_COMPOSE_PROJECT` environment will let you configure this. 

Make sure you are getting Docker Extension `v1.1.1606092330` in your virtual machines to use this functionality.

We had some problems publishing the new version of the extension this week even though we had the fix on Monday. Please let us know how it works out for you.
