### ISSUE TITLE
Cannot specify compose http timeout

### ISSUE THREAD

**Issue by alinamstanciu** [Azure/azure-docker-extension#87]
There’s no way to specify the COMPOSE_HTTP_TIMEOUT, so any moderately complicated compose projects (like ours) will always fail

**Comment by ahmetalpbalkan** [comment]
@alinamstanciu thanks for reporting. we actually set COMPOSE_HTTP_TIMEOUT=600 while executing docker-compose.

If I recall correctly, this should not be related to how big the docker images are. While a docker image is pulled, docker-engine keeps sending updates back to the client, in this case docker-compose. I will confirm all this with docker devs.

How big are your images?

**Comment by vishwam** [comment]
I'm composing 8 images each around 700MB, but they're almost all based on node:latest so the total download size should be ~2GB. You're correct, though: according to the documentation, the image size shouldn't matter, but I've observed my docker-compose fails consistently with a 10 minute timeout, and slightly less consistently with a 15 minute one.

My current workaround is to do a `docker-compose pull` first, and then `docker-compose up`. I think this has the added benefit of ensuring you're actually using the image version that's listed on the hub (useful if an image was previously downloaded on the machine, but a new image has been published with the same tag)

**Comment by ahmetalpbalkan** [comment]
@vishwam  Please look at the newly added `compose-environment` key in the README. Specifying the `COMPOSE_HTTP_TIMEOUT ` environment variable there will let you configure this setting passed to `docker-compose`.

Make sure you are getting Docker Extension `v1.1.1606092330` in your virtual machines to use this new functionality.
