### ISSUE TITLE
[integration-test] Timeout for indefinite retries

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-docker-extension#89]
Our integration tests validate a number of things by deploying VMs and running commands against them via docker-cli. However since extension deployment to VM happens async, we keep retrying. 

Problem is we currently retry indefinitely (and keep printing `.`s to the screen every 5 s.). We should fail after a while with a good error message.

**Comment by boumenot** [comment]
The Docker extension has been [deprecated](https://github.com/Azure/azure-docker-extension/wiki/Deprecation-Notice).
