### ISSUE TITLE
Correct compose save path for CoreOS

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-docker-extension#9]
`enable.sh` fails to download docker-compose because

    MSOpenTech.Extensions.DockerExtension-0.6.0.0/scripts/enable.sh: line 84: /usr/local/bin/docker-compose: Read-only file system

on CoreOS paths like /usr/bin, /bin/, /usr/local/bin will be readonly.

This causes script to terminate early and not make it to steps like configuring certs and DOCKER_OPTS.

**Comment by ahmetalpbalkan** [comment]
Fixed in #20

**Comment by JulianKingman** [comment]
I'm having this issue setting up compose.

**Comment by ahmetalpbalkan** [comment]
@JulianKingman So this was a pretty old issue in the old extension (`MSOpenTech.Extensions.DockerExtension`). Are you using that or the new `Microsoft.Azure.Extensions.DockerExtension`? We recommend migration to the new one: https://azure.microsoft.com/en-us/blog/a-brand-new-docker-extension/ the old one will be removed on Dec 1st, 2015.
